name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
